<?php

return [
    'course_catalog' => [
        'AWR-213' => 'Consortium Course AWR-213',
        'AWR-232' => 'Mass Fatalities Planning and Response for Rural Communities',
        'E/G/K-2300' => 'Intermediate Emergency Operations Center Functions',
        'EOC-101' => 'Emergency Operations Center Orientation',
        'FL-393' => 'Mitigation for Emergency Managers',
        'FL-601' => 'Preliminary Damage Assessment',
        'FL-603(f)' => 'Public Assistance 101 & Grants Management',
        'FL-608(f)' => 'Emergency Work Eligibility',
        'FL-609(f)' => 'Permanent Work Eligibility',
        'FL-680' => 'Individual Assistance: The Local Role',
        'FL-681' => 'Florida Course 681',
        'FL-S.B.180' => 'Florida Senior Elected Officials Course',
        'FROC-653' => 'Florida Recovery Operations Course 653',
        'FROC-656' => 'Florida Recovery Operations Course 656',
        'G-141' => 'Instructional Presentation and Evaluation Skills',
        'G-191' => 'Emergency Operations Center/Incident Command System Interface',
        'G-205' => 'Recovery from Disaster: The Local Government Role',
        'G-2304' => 'Emergency Operations Center Planning Skillset',
        'G-2308' => 'Emergency Operations Center Operations and Situational Awareness Skillsets',
        'G-235' => 'Emergency Planning',
        'G-300' => 'Intermediate Incident Command System for Expanding Incidents',
        'G-393' => 'Mitigation for Emergency Managers',
        'G-400' => 'Advanced Incident Command System Command & General Staff: Complex Incidents',
        'G-557' => 'Rapid Needs Assessment',
        'ICS-100' => 'Introduction to the Incident Command System',
        'ICS-200' => 'Basic Incident Command System',
        'ICS-300' => 'Intermediate ICS',
        'ICS-400' => 'Advanced ICS',
        'L-105' => 'Public Information Basics',
        'L-146' => 'Homeland Security Exercise and Evaluation Program Training Course',
        'L-449' => 'Incident Command System Curricula Train-the-Trainer',
        'L-950' => 'NIMS ICS All-Hazards Incident Commander',
        'L-958' => 'NIMS ICS All-Hazards Position Specific Operations Section Chief (OSC) Course',
        'L-960' => 'NIMS ICS All-Hazard Division & Group Supervisor',
        'L-964' => 'Situation Unit Leader (SITL) in an all-hazards incident',
        'L-965' => 'NIMS ICS All-Hazards Resources and Demobilization Unit Leaders',
        'L-987' => 'NIMS ICS All-Hazards Introduction to Air Operations',
        'L-1301' => 'Continuity Planning',
        'L-1302' => 'Continuity Program Management',
        'MGT-307' => 'Consortium Course MGT-307',
        'MGT-310' => 'Consortium Course MGT-310',
        'MGT-315' => 'Consortium Course MGT-315',
        'MGT-318' => 'Public Information in an All-Hazards Incident',
        'MGT-319' => 'Medical Countermeasures: Points of Dispensing (POD), Planning and Response',
        'MGT-340' => 'Crisis Leadership & Decision Making for Elected Officials',
        'MGT-345' => 'Disaster Management for Electric Power Systems',
        'MGT-361' => 'Consortium Course MGT-361',
        'MGT-414' => 'Critical Infrastructure Resilience and Community Lifelines',
        'MGT-415' => 'Disaster Recovery in Rural Communities',
        'MGT-439' => 'Pediatric Disaster Response and Emergency Preparedness',
        'MGT-452' => 'Consortium Course MGT-452',
        'MGT-465' => 'Recovering from Cybersecurity Incidents',
        'PER-211' => 'Medical Management of CBRNE Events',
        'PER-257' => 'Cybersecurity First Responder',
        'PER-348' => 'Operations Level Response to Radiological/Nuclear WMD',
        'WebEOC' => 'WebEOC Training',
    ],
    'courses_not_in_current_fdem_catalog' => [
        'AWR-213', 'EOC-101', 'FL-393', 'FL-681', 'FROC-653', 'FROC-656',
        'G-2304', 'G-393', 'ICS-100', 'ICS-200', 'ICS-300', 'ICS-400',
        'L-1301', 'L-1302', 'L-449', 'MGT-307', 'MGT-310', 'MGT-315',
        'MGT-361', 'MGT-452', 'WebEOC',
    ],
    'uncoded_fdem_catalog_entries' => [
        '2026 F-ROC Training Tour - Exercise Recovery: The F-ROC Readiness Review',
        'Basic Floodplain Management for Florida Floodplain Administrators',
        'FLEX Basic User Orientation',
        'FLEX Instructor Orientation (Active State Approved Instructors Only)',
        'SEOC Foundations',
        'SEOC Foundations - Instructor Led',
        'WebEOC Foundations',
    ],
    'fdem_catalog_source' => 'https://fdemtraining.geniussis.com/learner/catalog',
    'fdem_catalog_reviewed_at' => '2026-08-17',
    'counties' => ['Polk', 'Hardee', 'DeSoto', 'Okeechobee', 'Highlands', 'Regional / Other'],
    'flex_statuses' => ['Not Checked', 'Not in FLEX', 'Pending', 'Approved', 'Expired', 'Suspended'],
    'delivery_roles' => ['Lead Instructor', 'Co-Instructor', 'Evaluator / Observer', 'Candidate'],
    'delivery_modes' => ['Any Delivery Mode', 'In Person', 'Virtual', 'Hybrid', 'Unknown'],
    'travel_options' => ['Yes', 'No', 'Unknown'],
    'availability' => ['Available', 'Limited', 'Not Available', 'Unknown'],
    'priority_options' => ['Yes', 'No', 'Unknown'],
    'review_statuses' => ['pending', 'verified', 'needs_changes', 'gap_identified'],
];
